#!/bin/sh
# 5298705 20110316
# usage: convert_package_list $package_list $repository_name

SLlist2roaring() {
#	echo "$package_list"
	while read LINE ; do
		case $LINE in
			"<package "*)
				while read nextLINE; do
					case $nextLINE in
						"<name>"*)
							NAME="${nextLINE%</*}";NAME="${NAME#*>}"
						;;
						"<version "*)
							VERSION="${nextLINE#*ver=\"}";VERSION="${VERSION%%\"*}"
							RELEASE="${nextLINE#*rel=\"}";RELEASE="${RELEASE%%\"*}"
						;;
						"<location href="*)
							LOCATION="${nextLINE#*=\"}";LOCATION="${LOCATION%%\"*}"
						;;
						"<summary>"*)
							DESCRIPTION="${nextLINE#*>}";DESCRIPTION="${DESCRIPTION%<*}"
						;;
						"</package>"*)
							echo "${NAME}|${VERSION}|${RELEASE}|${LOCATION}|${DESCRIPTION}">> $temp_file
							break
						;;
						*)
						;;
					esac
				done
			;;
			*)
			;;
		esac
  done < $package_list
}
repository_name="$2"
package_list="$1"
sed -i 's/></>\n</g' $package_list
temp_file="$(mktemp -u)"
SLlist2roaring
cat $temp_file
rm $temp_file 2>/dev/null
#pkgname|version|pkgrelease|path/fullfilename|description
