#!/bin/sh

# usage: extract_package $package $dest

# create the output directory
mkdir -p "$2"

# extract the package

#rpm2cpio $FULLPKGNAME | cpio -id > /dev/null 2>&1
rpm2cpio "$1" | cpio -id "$2"[ 0 -ne $? ] && exit 1

exit 0
